# Generated by Django 4.2.1 on 2023-06-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_gender_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='age_category',
            field=models.CharField(blank=True, choices=[('infant', 'infants'), ('girls', 'girls')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender_category',
            field=models.CharField(blank=True, choices=[('boys', 'boys'), ('girls', 'girls')], max_length=50),
        ),
    ]
