# Generated by Django 4.2.1 on 2023-06-19 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_brand'),
        ('store', '0004_product_age_category_alter_product_gender_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='age_category',
            field=models.CharField(blank=True, choices=[('infant', 'infant (0 - 2)'), ('toddler', 'toddler (3 - 5)'), ('little kids', 'little kids(6 - 12)')], max_length=50),
        ),
    ]
