# Generated by Django 3.2.7 on 2023-07-13 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_age'),
        ('store', '0006_reviewrating_productgallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='age_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.age'),
        ),
    ]
