# Generated by Django 3.2.7 on 2023-07-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_age_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='age_category',
            field=models.CharField(blank=True, choices=[('infant-0-2', 'Infant (0 - 2)'), ('toddler-3-5', 'toddler (3 - 5)'), ('little-kids-6-12', 'little kids(6 - 12)')], max_length=50, null=True),
        ),
    ]
