# Generated by Django 3.2.7 on 2023-07-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_product_is_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='variation',
            name='colors',
            field=models.ManyToManyField(related_name='variations', to='store.Color'),
        ),
    ]
