# Generated by Django 3.2.7 on 2023-07-14 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20230714_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrating',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='colors',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
