# Generated by Django 3.2.7 on 2023-07-15 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20230715_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
