# Generated by Django 3.2.7 on 2023-07-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_productvariation_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='color',
        ),
        migrations.AddField(
            model_name='productvariation',
            name='colors',
            field=models.ManyToManyField(blank=True, null=True, to='store.Color'),
        ),
    ]
