# Generated by Django 3.2.7 on 2023-07-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_auto_20230715_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='variation_value',
        ),
        migrations.AddField(
            model_name='variation',
            name='variation_value',
            field=models.ManyToManyField(blank=True, null=True, to='store.Color'),
        ),
    ]
