# Generated by Django 3.2.7 on 2023-07-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20230715_1952'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.AlterField(
            model_name='variation',
            name='variation_value',
            field=models.CharField(max_length=100),
        ),
    ]
