# Generated by Django 3.2.7 on 2023-07-17 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_faq_topic_faqs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqs',
            name='ordernumber',
        ),
    ]
