# Generated by Django 3.2.7 on 2023-07-17 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_policy_list'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='policy_list',
            new_name='Policy',
        ),
    ]
