# Generated by Django 3.2.7 on 2023-07-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_rename_policy_list_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='slug',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
