# Generated by Django 3.2.7 on 2023-07-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_rename_image_banner_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='images',
            field=models.ImageField(max_length=255, upload_to='images/banners'),
        ),
    ]
