# Generated by Django 3.2.7 on 2023-07-17 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_alter_banner_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
