# Generated by Django 4.2.1 on 2023-06-19 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='description',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
